"""Static F1 circuit data — laps, lengths, lap records."""

from typing import Optional, Dict, Any

CIRCUITS = [
    {
        "keywords": ["australian", "albert park"],
        "total_laps": 58,
        "circuit_length_km": 5.278,
        "lap_record_time": "1:19.813",
        "lap_record_driver": "C. Leclerc",
        "lap_record_year": 2022,
    },
    {
        "keywords": ["chinese", "shanghai"],
        "total_laps": 56,
        "circuit_length_km": 5.451,
        "lap_record_time": "1:32.238",
        "lap_record_driver": "M. Schumacher",
        "lap_record_year": 2004,
    },
    {
        "keywords": ["japanese", "suzuka"],
        "total_laps": 53,
        "circuit_length_km": 5.807,
        "lap_record_time": "1:30.983",
        "lap_record_driver": "L. Hamilton",
        "lap_record_year": 2019,
    },
    {
        "keywords": ["bahrain", "sakhir"],
        "total_laps": 57,
        "circuit_length_km": 5.412,
        "lap_record_time": "1:31.447",
        "lap_record_driver": "P. de la Rosa",
        "lap_record_year": 2005,
    },
    {
        "keywords": ["saudi", "jeddah"],
        "total_laps": 50,
        "circuit_length_km": 6.174,
        "lap_record_time": "1:30.734",
        "lap_record_driver": "L. Hamilton",
        "lap_record_year": 2021,
    },
    {
        "keywords": ["miami"],
        "total_laps": 57,
        "circuit_length_km": 5.412,
        "lap_record_time": "1:29.708",
        "lap_record_driver": "L. Norris",
        "lap_record_year": 2023,
    },
    {
        "keywords": ["emilia", "romagna", "imola"],
        "total_laps": 63,
        "circuit_length_km": 4.909,
        "lap_record_time": "1:15.484",
        "lap_record_driver": "V. Bottas",
        "lap_record_year": 2020,
    },
    {
        "keywords": ["monaco", "monte carlo"],
        "total_laps": 78,
        "circuit_length_km": 3.337,
        "lap_record_time": "1:14.260",
        "lap_record_driver": "L. Hamilton",
        "lap_record_year": 2021,
    },
    {
        "keywords": ["canadian", "montreal"],
        "total_laps": 70,
        "circuit_length_km": 4.361,
        "lap_record_time": "1:13.078",
        "lap_record_driver": "V. Bottas",
        "lap_record_year": 2019,
    },
    {
        "keywords": ["spanish", "barcelona", "cataluny"],
        "total_laps": 66,
        "circuit_length_km": 4.657,
        "lap_record_time": "1:16.330",
        "lap_record_driver": "M. Verstappen",
        "lap_record_year": 2023,
    },
    {
        "keywords": ["austrian", "spielberg", "red bull ring"],
        "total_laps": 71,
        "circuit_length_km": 4.318,
        "lap_record_time": "1:05.619",
        "lap_record_driver": "C. Sainz",
        "lap_record_year": 2020,
    },
    {
        "keywords": ["british", "silverstone"],
        "total_laps": 52,
        "circuit_length_km": 5.891,
        "lap_record_time": "1:27.097",
        "lap_record_driver": "L. Hamilton",
        "lap_record_year": 2020,
    },
    {
        "keywords": ["hungarian", "budapest", "hungaroring"],
        "total_laps": 70,
        "circuit_length_km": 4.381,
        "lap_record_time": "1:16.627",
        "lap_record_driver": "L. Hamilton",
        "lap_record_year": 2020,
    },
    {
        "keywords": ["belgian", "spa"],
        "total_laps": 44,
        "circuit_length_km": 7.004,
        "lap_record_time": "1:46.286",
        "lap_record_driver": "V. Bottas",
        "lap_record_year": 2018,
    },
    {
        "keywords": ["dutch", "netherlands", "zandvoort"],
        "total_laps": 72,
        "circuit_length_km": 4.259,
        "lap_record_time": "1:11.097",
        "lap_record_driver": "L. Hamilton",
        "lap_record_year": 2021,
    },
    {
        "keywords": ["italian", "monza"],
        "total_laps": 53,
        "circuit_length_km": 5.793,
        "lap_record_time": "1:21.046",
        "lap_record_driver": "R. Barrichello",
        "lap_record_year": 2004,
    },
    {
        "keywords": ["azerbaijan", "baku"],
        "total_laps": 51,
        "circuit_length_km": 6.003,
        "lap_record_time": "1:43.009",
        "lap_record_driver": "M. Verstappen",
        "lap_record_year": 2019,
    },
    {
        "keywords": ["singapore"],
        "total_laps": 62,
        "circuit_length_km": 4.940,
        "lap_record_time": "1:35.867",
        "lap_record_driver": "L. Hamilton",
        "lap_record_year": 2023,
    },
    {
        "keywords": ["united states", "cota", "austin"],
        "total_laps": 56,
        "circuit_length_km": 5.513,
        "lap_record_time": "1:36.169",
        "lap_record_driver": "C. Leclerc",
        "lap_record_year": 2019,
    },
    {
        "keywords": ["mexico", "mexico city"],
        "total_laps": 71,
        "circuit_length_km": 4.304,
        "lap_record_time": "1:17.774",
        "lap_record_driver": "V. Bottas",
        "lap_record_year": 2021,
    },
    {
        "keywords": ["brazil", "são paulo", "sao paulo", "interlagos"],
        "total_laps": 71,
        "circuit_length_km": 4.309,
        "lap_record_time": "1:10.540",
        "lap_record_driver": "V. Bottas",
        "lap_record_year": 2018,
    },
    {
        "keywords": ["las vegas"],
        "total_laps": 50,
        "circuit_length_km": 6.201,
        "lap_record_time": "1:35.490",
        "lap_record_driver": "L. Hamilton",
        "lap_record_year": 2023,
    },
    {
        "keywords": ["qatar", "lusail"],
        "total_laps": 57,
        "circuit_length_km": 5.419,
        "lap_record_time": "1:24.319",
        "lap_record_driver": "M. Verstappen",
        "lap_record_year": 2023,
    },
    {
        "keywords": ["abu dhabi", "yas"],
        "total_laps": 58,
        "circuit_length_km": 5.281,
        "lap_record_time": "1:26.103",
        "lap_record_driver": "M. Verstappen",
        "lap_record_year": 2021,
    },
]


def get_circuit_data(event_name: str) -> Optional[Dict[str, Any]]:
    """Return circuit data for a given EventName string, or None if not found."""
    name_lower = event_name.lower()
    for entry in CIRCUITS:
        if any(kw in name_lower for kw in entry["keywords"]):
            return entry
    return None
